name: Daily Update

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set up Git credentials
      run: |
        git config --global user.email "pds@mit.edu"
        git config --global user.name "Automated Map Updater"
    - name: Git pull
      run: |
        git pull
    - name: Make the map
      run: |
        python map.py
    - name: Commit back to the repo to update
      run: |
        git add .
        git commit -m "Automated daily update"
        git push
      
